import "./globals.css";

import Footer from "@/components/layout/Footer/Footer";
// app/layout.tsx
import type { Metadata } from "next";
import ScrollHeader from "@/components/layout/Header/ScrollHeader";

export const metadata: Metadata = {
  title: "Wood in Vision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
      </head>
      <body style={{ fontFamily: "euclid" }} className={`antialiased bg-[#0b0d12]`}>
        <div className="relative">
          {/* Background image */}
          <div
            style={{
              backgroundImage: "url('/images/background.jpg')",
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
            className="h-[965] w-full absolute  -z-2 top-0 left-0"
          />
          <div className="h-[965px] w-full absolute -z-1 top-0 left-0 shadow-[0_40px_150px_-20px_rgba(0,0,0,0.9)] bg-gradient-to-b from-black/40 to-black/85" />
          <main>
            <ScrollHeader />

            <div className="relative px-4 max-w-[78.5rem] mx-auto">{children}</div>
          </main>
            <div>
              <Footer />
            </div>
        </div>
      </body>
    </html>
  );
}
